core/urls.py
from django.urls import path
from core import views
app_name= "core"
urlpatterns= [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),

    #feedback
    path("feedback/create", views.feedback_createview, name="feedback_create"),
    path("feedback/list/",views.feedback_listview, name="feedback_list"),
    # service booking
    path("service/",views.BookServiceView.as_view(),name="book_service"),
    path("service/<int:pk>/delivery",views.ServiceView.as_view(),name="delivery"),
    path("service/history/",views.BookServiceListView.as_view(),name="service_history"),
    # payment
    path("service/<int:pk>/checkout/",views.CheckoutView.as_view(),name="checkout"),
    path("service/<int:pk>/payment/",views.PaymentView.as_view(),name="payment"),
    path("service/<int:pk>/payment/completed/",views.PaymentCompletedView.as_view(),name="payment_completed"),
    # Payment
    path("payment/list/", views.PaymentListView.as_view(), name="payment_list"),


]

online_vehicle_service/urls.py
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path("user/", include("django.contrib.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from core import views
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="user_signup"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
       # profile
    path("profile/create", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/detail", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    
]

core/models.py
import datetime
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.db import models


class TimeStamp(models.Model):
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class FeedbackModel(TimeStamp, models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()
    subject = models.CharField(max_length=120)
    message = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.name}"

    
#bookservice

# Vehicle Model
class VehicleModel(TimeStamp, models.Model):
    class VehicleType(models.TextChoices):
        MOTOR_CYCLE = "mc", "Motor Cycle"
        CAR = "cr", "Car"
        HEAVY_VEHICLE = "hv", "Heavy Vehicle"

    name = models.CharField(max_length=120)

    model = models.CharField(max_length=64)
    type = models.CharField(max_length=18, choices=VehicleType.choices)

    def __str__(self):
        return f"{self.name}"


# Service Type
class ServiceTypeModel(TimeStamp, models.Model):
    name = models.CharField(max_length=64)
    cost = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.name}"


# Service Model
class ServiceModel(TimeStamp, models.Model):
    USER = get_user_model()
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    type = models.ForeignKey(ServiceTypeModel, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(VehicleModel, on_delete=models.CASCADE)

    cost = models.FloatField(default=0.0)
    date = models.DateTimeField()
    delivery_time = models.DateTimeField(default=timezone.now)
    is_delivered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.vehicle}-{self.type}"

    def save(self, *args, **kwargs):
        id = self.id
        if id is None:
            self.cost = self.type.cost
        return super().save(*args, **kwargs)

    

#payment
class Payment(TimeStamp, models.Model):
    class PaymentStatusChoices:
        pending = "pending"
        completed = "completed"
        failed = "failed"

    PAYMENT_STATUS_CHOICES = (
        ("Pending", PaymentStatusChoices.pending),
        ("Completed", PaymentStatusChoices.completed),
        ("Failed", PaymentStatusChoices.failed),
    )
    status = models.CharField(
        max_length=16,
        choices=PAYMENT_STATUS_CHOICES,
        default=PaymentStatusChoices.pending,
    )
    mode = models.CharField(max_length=50, null=True, blank=True)
    razorpay_order_id = models.CharField(max_length=256)
    razorpay_payment_id = models.CharField(max_length=256)
    razorpay_amount = models.FloatField(),
    razorpay_currency =  models.CharField(max_length=16)

    def __str__(self):
        return f"{self.razorpay_order_id} - ({self.status})"

core/forms.py
from django import forms

from core import models


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.FeedbackModel
        exclude = ("status",)


class ServiceForm(forms.ModelForm):
    class Meta:
        model = models.ServiceModel
        fields = ["type", "vehicle", "date"]


class PaymentForm(forms.Form):
    PAYMENT_CHOICES = (("UPI", "UPI"), ("NETBANK", "Net Banking"))
    amount = forms.DecimalField(
        min_value=1, widget=forms.NumberInput(attrs={"readonly": "true"})
    )
    payment_method = forms.ChoiceField(choices=PAYMENT_CHOICES)

core/views.py
import razorpay
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views
from django.http import HttpResponse

from core import forms as core_forms
from core import models as core_models
from django.conf import settings
import core.payment as payment
from core import payment


class HomeView(views.TemplateView):
    template_name = "core/home.html"


class AboutView(views.TemplateView):
    template_name = "core/about.html"


# feedback createview
def feedback_createview(request):
    template_name = "core/feedback_create.html"
    form_class = core_forms.FeedbackForm
    success_url = reverse_lazy("core:home")

    if request.method == "GET":
        context = {"form": core_forms.FeedbackForm()}
        return render(request, template_name, context)

    elif request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(success_url)
        return render(request, template_name, {"form": form})


# feedback listview
def feedback_listview(request):
    template_name = "core/feedback_list.html"
    model = core_models.FeedbackModel

    if request.method == "GET":
        feedbacks = model.objects.all()
        context = {"feedbacks": feedbacks}
    return render(request, template_name, context)


# bookservice view
class BookServiceView(LoginRequiredMixin, views.CreateView):
    template_name = "core/service.html"
    form_class = core_forms.ServiceForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "succesfully submitted")
        return super().form_valid(form)

    def get_success_url(self):
        service = self.object
        url = reverse_lazy("core:checkout", kwargs={"pk": service.id})
        return url


# Checkout view
class CheckoutView(views.DetailView):
    template_name = "core/checkout.html"
    model = core_models.ServiceModel
    context_object_name = "service"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        amount = self.object.cost
        context["form"] = core_forms.PaymentForm(initial={"amount": amount})
        return context


# Payment View
# class PaymentView(views.View):
#     template_name = "core/payment.html"

#     success_url = ""

#     def get(self, request, *args, **kwargs):
#         pk = kwargs.get("pk")
#         service = core_models.ServiceModel.objects.get(id=pk)
#         context = {"service": service}

#         return render(request, self.template_name, context)

#     def post(self, request, *args, **kwargs):
#         form = core_forms.PaymentForm(request.POST)
#         return render(request, self.template_name)


class ServiceView(views.ListView):
    template_name = "core/Payment.html"
    model = core_models.ServiceModel
    context_object_name = "services"


# ================================================ #
# Payment Realated views                           #
# ================================================ #
# Payment view
class PaymentView(LoginRequiredMixin, views.View):
    template_name = "core/pay.html"
    RAZORPAY_CLIENT = razorpay.Client(
        auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET)
    )

    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        service = core_models.ServiceModel.objects.get(id=pk)
        client = self.RAZORPAY_CLIENT
        # params
        amount = service.cost
        currency = "INR"
        payment_capture = "1"
        callback_url = reverse_lazy(
            "core:payment_completed", kwargs={"pk": kwargs.get("pk")}
        )

        order = payment.create_order(
            client, amount, callback_url, receipt=None, currency=currency
        )
        print(order)
        context = {}
        context.update(order)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        try:
            # get the required parameters from post request.
            payment_id = request.POST.get("razorpay_payment_id", "")
            amount = request.POST.get("razorpay_amount", "0")
            razorpay_order_id = request.POST.get("razorpay_order_id", "")
            signature = request.POST.get("razorpay_signature", "")

            params_dict = {
                "razorpay_order_id": razorpay_order_id,
                "razorpay_payment_id": payment_id,
                "razorpay_signature": signature,
            }
            print("#DEBUG: Amount", type(amount), amount)
            try:
                amount = int(float(amount)) / 100
            except Exception as e:
                print("#DEBUG: amount can be converted into integer", e)
                amount = 5000
            print("#DEBUG: verifying the payment signature...", params_dict, amount)

            # verify the payment signature.
            result = self.RAZORPAY_CLIENT.utility.verify_payment_signature(params_dict)
            print("#DEBUG: verifying the payment signature... Completed.")

            if result is not None:

                try:
                    print("#DEBUG: Payment capturing...")
                    # capture the payment
                    self.RAZORPAY_CLIENT.payment.capture(payment_id, amount)
                    print("#DEBUG: Payment captured...")
                    print("#DEBUG: Payment model creating...")

                    core_models.Payment.objects.create(
                        razorpay_order_id=razorpay_order_id,
                        razorpay_payment_id=payment_id,
                        status=core_models.Payment.PaymentStatusChoices.completed,
                        mode="",
                    )
                    print("#DEBUG: Payment model created...")

                    # render success page on successful caputre of payment
                    return render(request, "core/paymentsuccess.html")
                except Exception as e:
                    print("#DEBUG: there is an error while capturing payment...", e)

                    # if there is an error while capturing payment.
                    return render(request, "core/paymentfail.html")
            else:
                print("#DEBUG: signature verification failed...", e)
                # if signature verification fails.
                return render(request, "core/paymentfail.html")
        except Exception as e:
            print("#DEBUG: we don't find the required parameters in POST data", e)
            # if we don't find the required parameters in POST data
            return redirect(
                reverse_lazy(
                    "core:payment_completed", kwargs={"pk": self.kwargs.get("pk")}
                )
            )


# payment completed
class PaymentCompletedView(views.TemplateView):
    template_name = "core/payment_completed.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        service = core_models.ServiceModel.objects.get(id=pk)
        context["service"] = service
        return context


# payment List view
class PaymentListView(LoginRequiredMixin, views.ListView):
    template_name = "core/payment_list.html"
    model = core_models.Payment
    context_object_name = "payments"

    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        qs = qs.filter(order__cart__user=user)
        return qs


# history
class BookServiceListView(LoginRequiredMixin, views.ListView):
    template_name = "core/history.html"
    model = core_models.ServiceModel
    context_object_name = "services"

templates/core/bike.html
{% extends 'base.html' %}
{% block content %}
<body class="bike">
<section>
<div class="container py-5 ">
    <div class="row">
        <div class="col-lg-6">
          <h1>BIKES</h1>
          <p>
            MotoHub is an exclusive hub for all kind of vehicle services.We provide quick services for your vehicles.
            your experience matters to us.Please comment down your experince with us.  
                Thankyou 
          </p>
        </div>
        <div class="col-lg-6">
          <div class="card text-light bg-dark">
            <div class="card-body">
              <form action="" method="post">
                {% csrf_token %}
                <table>
                    <tbody>
                        {{form.as_p}}
                    </tbody>
                </table>
                <button class="btn btn-primary" type="submit">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
</div>
</section>
</body>

{% endblock content %}

templates/core/checkout.html
{% extends 'base.html' %} {% block content %}
<section style="min-height: 100vh">
  <div class="container-fluid bg-light login vh-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-lg-7 px-4">
        <div class="px-4">
          <div class="card bg-dark text-light">
            <div class="card-body">
              <p class="card-title text">
                * Your Service Cost : {{service.cost}}
              </p>
              <br />
              <div class="card-text">
                <p class="card-title text">
                  * Type Of Service : {{service.type}}
                </p>
                <br />
                <p class="card-title text">
                  * Your Vehicle : {{service.vehicle}}
                </p>
              </div>
              <br />
              <div>
                <a
                  href="{% url 'core:payment' service.id %}"
                  class="btn btn-primary"
                  >Pay</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/core/feedback_create.html
{% extends 'base.html' %} {% block content %}

<section class="bg-dark">
  <div class="container list m-0 me-0">
    <div class="row">
      <div class="col-lg-6">
        <h1>Feedback form</h1>
        <p>
          MotoHub is an exclusive hub for all kind of vehicle services.We provide quick services for your vehicles.
          your experience matters to us.Please comment down your experince with us.  
              Thankyou 
        </p>
      </div>
      <div class="col-lg-6">
        <div class="card bg-dark text-light">
          <div class="card-body">
            <form action="" method="post">
              {% csrf_token %}
              <table>
                  <tbody>
                      {{form.as_p}}
                  </tbody>
              </table>
              <button class="btn btn-primary" type="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/core/feedback_list.html
{% extends "base.html" %} {% block content %}
<div class= "feedback">

<section class="py-5">
  <div class="container">
    <div class="row">
        <div class="col">
            <h2 class="text-center">Feedback List</h2>
            <hr>
        </div>
    </div>
    <div class="row">
      <div class="col">
        {% for feedback in feedbacks %}
        <div class="card fblist">
          <div class="card-body">
            <div class="card-title">
              <p class="fb-color">Name : {{feedback.name}}</p>
            </div>
            <div class="card-text">
              <p class="fb-color">Message : {{feedback.message}}</p>
              <p class="fb-color">Updated Date : {{feedback.updated_on|date}}</p>
            </div>
          </div>
          {% empty %}
            <div>
              <p class="fb-color">No feedbacks!</p>
            </div>
            {% endfor %}

        </div>
        <!-- <table class="table table-bordered align-middle">
          <thead>
            <tr class="text-center fw-bold">
              <th >#</th>
              <th>Name</th>
              <th>Subject</th>
              <th>Last Updated</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for feedback in feedbacks %}

            <tr>
              <td class="text-center fw-bold">{{forloop.counter}}</td>
              <td>{{feedback.name}}</td>
              <td>{{feedback.subject}}</td>
              <td>{{feedback.updated_on|date}}</td>
              <td>{{feedback.message}}</td>
            </tr>

            {% empty %}
            <tr>
              <td colspan="4">No feedbacks!</td>
            </tr>
            {% endfor %}
          </tbody>
        </table> -->
      </div>
    </div>
  </div>
</section>
</div>

{% endblock content %}

templates/core/history.html
{% extends 'base.html' %} {% block content %}
<section>
    <div class="history bg-dark container">
        <div class="row">
           
            {% for service in services %}
            <div class="row row-cols-1 row-cols-md-1 g-4">
                <div class="col">
                  <div class="card bg-dark text-light text-center">
                   
                    <div class="card-body ">
                        <p class="card-text">User :<strong>{{service.user}}</strong></p>
                        <p class="card-text">Type : {{service.type}}</p>
                        <p class="card-text">cost : {{service.cost}}</p>
                        <p class="card-text">Date : {{service.date}}</p>
                        <p class="card-text">Is Delivered : {{service.is_delivered}}</p>
                       
                      
                    </div>
                  </div>
                </div>
            </div>

        {% empty %}
        <div class="col">
          <p>no services</p>
        </div>
        {% endfor %}

    </div>
</section>

{% endblock content %}

templates/core/home.html
{% extends 'base.html' %}

{% block content %}

<section class=" bg-home">
    <div class = "text-center bg-dark"><h2>MOTOHUB SERVICES</h2></div>
    <section class="hero-section">
        <div
          id="carouselExampleControls"
          class="carousel slide h-100"
          data-bs-ride="carousel"
        >
          <div class="carousel-inner h-100">
            <div class="carousel-item active h-100">
              <img src="media/default/prj1.png" class="d-block w-100 h-100" alt="" />
            </div>
            <div class="carousel-item h-100">
              <img src="media/default/prj4.png" class="d-block w-100 h-100" alt="" />
            </div>
          </div>
          <button
            class="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleControls"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button
            class="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleControls"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </section>

      <div>
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<a href="{% url 'core:book_service' %}"><button class="btns text-center">Book Services</button></a>
      </div>
      <br>
      <br>
      <div class="card-group">
        <div class="card">
          <img src="media\default\prj8.png" class="card-img-top" alt="...">
          <div class="card-body white bg-dark">
            <h5 class="card-title">ENGINE TUNE-UP</h5>
            <p class="card-text">Proper Engine Tuning</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            <a href="{% url 'core:book_service' %}"><button type="button" class="btn btn-success">Book Now</button></a>
          </div>
        </div>
        <div class="card">
          <img src="media\default\prj7.png" class="card-img-top" alt="...">
          <div class="card-body white bg-dark">
            <h5 class="card-title">FILTER CHANGE</h5>
            <p class="card-text">Lub/Oil Filter chnage </p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            <a href="{% url 'core:book_service' %}"><button type="button" class="btn btn-success">Book Now</button></a>
          </div>
        </div>
        <div class="card">
          <img src="media\default\prj9.png" class="card-img-top" alt="...">
          <div class="card-body white bg-dark">
            <h5 class="card-title">WHEEL ALIGNMENT</h5>
            <p class="card-text">Proper Wheel alignment</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            <a href="{% url 'core:book_service' %}"><button type="button" class="btn btn-success">Book Now</button></a>
          </div>
        </div>
      </div>
        
<br>
<br>

</div>
<br>
<div class="card-group">
  <div class="card">
    <img src="media\default\prj10.png" class="card-img-top" alt="..." style="height:250px">
    <div class="card-body white bg-dark">
      <h5 class="card-title">WATER SERVICE</h5>
      <p class="card-text">Experience the best water service</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <a href="{% url 'core:book_service' %}"><button type="button" class="btn btn-success">Book Now</button></a>
    </div>
  </div></style>
  <div class="card">
    <img src="media\default\prj11.png" class="card-img-top" alt="..." style="height:250px">
    <div class="card-body white bg-dark">
      <h5 class="card-title">NEW TIRES</h5>
      <p class="card-text">New Tires Available</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <a href="{% url 'core:book_service' %}"><button type="button" class="btn btn-success">Book Now</button></a>
    </div>
  </div></style>
  <div class="card">
    <img src="media\default\prj12.png" class="card-img-top" alt="..." style="height:250px">
    <div class="card-body white bg-dark">
      <h5 class="card-title">BATTERY REPLACEMENT</h5>
      <p class="card-text">Full Battery Replacement</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <a href="{% url 'core:book_service' %}"><button type="button" class="btn btn-success">Book Now</button></a>
    </div>
  </div></style>
  </div>
</div>

<br>
<br>
<br>
<br>

</section>

{% endblock content %}

templates/core/hv.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container hv py-5">
    <div class="row">
        <div class="col-lg-6">
          <h1>HEAVY VEHICLES</h1>
          <p>
            MotoHub is an exclusive hub for all kind of vehicle services.We provide quick services for your vehicles.
            your experience matters to us.Please comment down your experince with us.  
                Thankyou 
          </p>
        </div>
        <div class="col-lg-6">
          <div class="card">
            <div class="card-body">
              <form action="" method="post">
                {% csrf_token %}
                <table>
                    <tbody>
                        {{form.as_p}}
                    </tbody>
                </table>
                <button class="btn btn-primary" type="submit">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
</div>
</section>

{% endblock content %}

templates/core/payment_completed.html
{% extends 'base.html' %} {% block content %}
<!-- breadcrumb-section -->
<div class= " final breadcrumb-section breadcrumb-bg">
  <div class="min-vh-100 container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 text-center">
        <div class="breadcrumb-text">
          <h5 class="bg-dark text-light text-success">
            Payment was successfull!
            <span>
              <div class="bg-dark text-light card-body">
                <p>Delivery Expected on : {{service.delivery_time}}</p>
            </div>

              Back to
              <a href="{% url 'core:home' %}" class="link-primary">home</a>
            </span>
          </h5>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end breadcrumb section -->

{% endblock %}

templates/core/payment_fail.html
{% extends 'base.html' %} 

{% block content %}

<h5 class="text-danger">
  Payment failed!
  <span>
    Back to <a href="{% url 'core:home' %}" class="link-primary">home</a>
  </span>
</h5>

{% endblock %}

templates/core/payment_success.html
{% extends 'base.html' %} {% block content %}
<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 text-center">
        <div class="breadcrumb-text">
          <h5 class="text-success">
            Payment was successfull!
            <span>
              Back to
              <a href="{% url 'core:home' %}" class="link-primary">home</a>
            </span>
          </h5>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end breadcrumb section -->

{% endblock %}

templates/core/profile.html
{% extends 'base.html' %}{% block content %}

<section class=" bg-dark gradient-custom-2" style="min-height:100vh">  
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div
            class="rounded-top text-white d-flex flex-row"
            style="background-color: #000; height: 200px"
          >
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px">
              {% if user.profilemodel %}             
                <img
                id="profileImage"
                src="{{user.profilemodel.image.url}}"
                alt="Generic placeholder image"
                class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 150px; z-index: 1"
                />         
             
              
              <button
                type="button"
                class="btn btn-outline-dark"
                data-mdb-ripple-color="dark"
                style="z-index: 1"
              >
                <a href="{% url 'user:profile_update' user.profilemodel.id %}">Edit profile
              </button></a>
            </div>
            <div class="ms-3" style="margin-top: 130px">
              <h5 class="text-capitalize">{{user.profilemodel.user}}</h5>
              <p>{{user.profilemodel.city}}Kochi</p>
            </div>
          </div>
          <div class="p-4 text-light" style="background-color: black">
            <div class="d-flex justify-content-end text-center py-1">
              <div class="mx-3">
                <p class="mb-1 h5"><i class="fa-regular fa-heart"></i></p>
                <p class="small text-muted mb-0">Favourites</p>
              </div>              
              <div lass="mx-3">
                <p class="mb-1 h5">478</p>
                <p class="small text-muted mb-0">Following</p>
              </div>
            </div>
          </div>
            <div class="card-body p-4 bg-dark text-light">
              <div class="mb-5">
                <p class="lead fw-normal mb-1">About</p>
                <div class="p-4 text-light" style="background-color: black">
                  <p class="font-italic mb-1 text-capitalize">
                    First_name : {{user.profilemodel.first_name}}</p>
                  <p class="font-italic mb-1 text-capitalize">
                    Last_name : {{user.profilemodel.last_name}}</p>
                  <p class="font-italic mb-1 text-capitalize">
                    Gender : {{user.profilemodel.gender}}</p>
                  <p class="font-italic mb-1">
                    phone_number : {{user.profilemodel.phone}}</p>
                  <form action="{% url 'user:profile_update' user.profilemodel.id %}" id="profileimageupdate" enctype="multipart/form-data">
                   {% csrf_token %}
                    <input id="imageUpload" type="file" 
                    name="profile_photo" placeholder="Photo" required="" capture>
                  </form>
                  
                </div>
             
              </div> 
              {% else %}
                <tr>
                  <td colspan="4">
                    <a href="{% url 'user:profile_create' %}" class="text-light">
                    Create Profile
                    </a>
                  </td>
                </tr>             
              {% endif %}                    
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/core/profile_create.html
{% extends 'base.html' %} {% block content %}
<section class="bg-dark">
    <div class="container py-5 " style="min-height:100vh ;">
        <div class="row">
          <h1 class="text-light">Create Profile</h1>    
          <div class="col-lg-6">
            <div class="card bg-dark text-light">
              <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <table>
                    <tbody>
                      {{form.as_p}}
                    </tbody>
                  </table>
                  <button class="btn btn-primary" type="submit">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
</section>
{% include 'includes/footer.html' %}
{% endblock content %}