core/urls.py
from django.urls import path
from core import views
app_name= "core"
urlpatterns= [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),

    #feedback
    path("feedback/create", views.feedback_createview, name="feedback_create"),
    path("feedback/list/",views.feedback_listview, name="feedback_list"),
    # service booking
    path("service/",views.BookServiceView.as_view(),name="book_service"),
    path("service/<int:pk>/delivery",views.ServiceView.as_view(),name="delivery"),
    path("service/history/",views.BookServiceListView.as_view(),name="service_history"),
    # payment
    path("service/<int:pk>/checkout/",views.CheckoutView.as_view(),name="checkout"),
    path("service/<int:pk>/payment/",views.PaymentView.as_view(),name="payment"),
    path("service/<int:pk>/payment/completed/",views.PaymentCompletedView.as_view(),name="payment_completed"),
    # Payment
    path("payment/list/", views.PaymentListView.as_view(), name="payment_list"),


]

online_vehicle_service/urls.py
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path("user/", include("django.contrib.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from core import views
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="user_signup"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
       # profile
    path("profile/create", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/detail", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    
]

templates/includes/footer.html
<footer class="bg-dark text-center text-white" style="min-width:100vw ;">

    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
  </footer>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-color">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:home' %}">MotoHub</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-center me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Feedback</a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'core:feedback_create' %}">Create Feedback</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:feedback_list' %}">View Feedbacks</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:book_service' %}">Book Service</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:service_history' %}">Your Bookings</a>
        </li>

        <li>

          {% if user.is_authenticated %}
            {% if user.profilemodel %}
            <a href="{% url 'user:profile_detail' user.profilemodel.id  %}" class="text-dark ms-2 me-2"
              style="text-decoration:None;">
              {{user}}
            </a>
            {% else %}
            <a href="{% url 'user:profile_create'  %}" class="text-dark ms-2 me-2" style="text-decoration:None;">
              {{user}}
            </a>
            {% endif %}
            {% else %}
            <a href="{% url 'user:user_signup' %}" class="text-dark ms-2 me-2" style="text-decoration:None;">
              Sign Up
            </a>
            {% endif %}
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item me-3">
          <a href="{% url 'user:user_logout' %}" class="text-dark ms-2 me-2 " style="text-decoration:None;">Logout</a>
          {% else %}
          <a href="{% url 'user:user_login' %}" class="text-dark ms-2 me-2" style="text-decoration: None;">
            Login
          </a>
          {% endif %}
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:about' %}">About us</a>
        </li>
      </ul>
      Welcome To MotoHub
    </div>
  </div>
</nav>

templates/includes/scripts.html
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'bootstrap-5.2.1-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'fontawesome-free-6.2.0-web/js/all.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

<!-- courosel -->

templates/includes/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'bootstrap-5.2.1-dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome-free-6.2.0-web/css/all.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- courosel -->